//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int Lecture1 { get; set; }
        public string LectureName { get; set; }
        public string Lecturer { get; set; }
        public string LectureCode { get; set; }
    }
}
